image:
  file: .gitpod.Dockerfile
tasks:
- before: >
    source ~/.bashrc
  init: >
    flutter pub get &&
    npm i -g firebase-tools
vscode:
  extensions:
    - Dart-Code.dart-code
    - Dart-Code.flutter
